### ISSUE TITLE
AttributeError: module 'tensorflow_federated.python' has no attribute 'federated_mean'

### ISSUE THREAD

**Issue by INERKIDFYN** [tensorflow/federated#262]
When i execute image classification example(Customizing the model implementation) on PyCharm in the link below:
https://github.com/tensorflow/federated/blob/master/docs/tutorials/federated_learning_for_image_classification.ipynb

wrong:
Traceback (most recent call last):
  File "/data/PycharmProjects/federated_learning/test.py", line 120, in <module>
    MnistTrainableModel)
  File "/home/BH/fyn123456/.conda/envs/py36/lib/python3.6/site-packages/tensorflow_federated/python/learning/federated_averaging.py", line 149, in build_federated_averaging_process
    model_fn, client_fed_avg, server_optimizer_fn)
  File "/home/BH/fyn123456/.conda/envs/py36/lib/python3.6/site-packages/tensorflow_federated/python/learning/framework/optimizer_utils.py", line 303, in build_model_delta_optimizer_process
    federated_dataset_type)
  File "/home/BH/fyn123456/.conda/envs/py36/lib/python3.6/site-packages/tensorflow_federated/python/core/impl/computation_wrapper.py", line 408, in <lambda>
    return lambda fn: _wrap(fn, arg_type, self._wrapper_fn)
  File "/home/BH/fyn123456/.conda/envs/py36/lib/python3.6/site-packages/tensorflow_federated/python/core/impl/computation_wrapper.py", line 96, in _wrap
    name=func_name)
  File "/home/BH/fyn123456/.conda/envs/py36/lib/python3.6/site-packages/tensorflow_federated/python/core/impl/computation_wrapper_instances.py", line 54, in _federated_computation_wrapper_fn
    suggested_name=name))
  File "/home/BH/fyn123456/.conda/envs/py36/lib/python3.6/site-packages/tensorflow_federated/python/core/impl/federated_computation_utils.py", line 75, in zero_or_one_arg_func_to_building_block
    parameter_name, parameter_type), context_stack))
  File "/home/BH/fyn123456/.conda/envs/py36/lib/python3.6/site-packages/tensorflow_federated/python/core/impl/func_utils.py", line 553, in <lambda>
    return (lambda fn, at, kt: lambda arg: _unpack_and_call(fn, at, kt, arg))(
  File "/home/BH/fyn123456/.conda/envs/py36/lib/python3.6/site-packages/tensorflow_federated/python/core/impl/func_utils.py", line 547, in _unpack_and_call
    return func(*args, **kwargs)
  File "/home/BH/fyn123456/.conda/envs/py36/lib/python3.6/site-packages/tensorflow_federated/python/learning/framework/optimizer_utils.py", line 394, in run_one_round_tff
    client_outputs.model_output)
  File "/home/BH/fyn123456/.conda/envs/py36/lib/python3.6/site-packages/tensorflow_federated/python/core/impl/func_utils.py", line 642, in __call__
    concrete_fn = self._concrete_function_factory(arg_type)
  File "/home/BH/fyn123456/.conda/envs/py36/lib/python3.6/site-packages/tensorflow_federated/python/core/impl/computation_wrapper.py", line 85, in <lambda>
    lambda pt: _wrap_polymorphic(wrapper_fn, func, pt))
  File "/home/BH/fyn123456/.conda/envs/py36/lib/python3.6/site-packages/tensorflow_federated/python/core/impl/computation_wrapper.py", line 82, in _wrap_polymorphic
    name=name)
  File "/home/BH/fyn123456/.conda/envs/py36/lib/python3.6/site-packages/tensorflow_federated/python/core/impl/computation_wrapper_instances.py", line 54, in _federated_computation_wrapper_fn
    suggested_name=name))
  File "/home/BH/fyn123456/.conda/envs/py36/lib/python3.6/site-packages/tensorflow_federated/python/core/impl/federated_computation_utils.py", line 75, in zero_or_one_arg_func_to_building_block
    parameter_name, parameter_type), context_stack))
  File "/home/BH/fyn123456/.conda/envs/py36/lib/python3.6/site-packages/tensorflow_federated/python/core/impl/func_utils.py", line 553, in <lambda>
    return (lambda fn, at, kt: lambda arg: _unpack_and_call(fn, at, kt, arg))(
  File "/home/BH/fyn123456/.conda/envs/py36/lib/python3.6/site-packages/tensorflow_federated/python/core/impl/func_utils.py", line 547, in _unpack_and_call
    return func(*args, **kwargs)
  File "/data/PycharmProjects/federated_learning/test.py", line 60, in aggregate_mnist_metrics_across_clients
    'loss': tff.federated_mean(metrics.loss, metrics.num_examples),
AttributeError: module 'tensorflow_federated.python' has no attribute 'federated_mean'

my code:
import collections
import numpy as np
import tensorflow as tf
from tensorflow_federated import python as tff

tf.compat.v1.enable_v2_behavior()

#Defining model variables,forward pass,and metrics
MnistVariables = collections.namedtuple(
    'MnistVariables', 'weights bias num_examples loss_sum accuracy_sum')

def create_mnist_variables():
  return MnistVariables(
      weights = tf.Variable(
          lambda: tf.zeros(dtype=tf.float32, shape=(784, 10)),
          name='weights',
          trainable=True),
      bias = tf.Variable(
          lambda: tf.zeros(dtype=tf.float32, shape=(10)),
          name='bias',
          trainable=True),
      num_examples = tf.Variable(0.0, name='num_examples', trainable=False),
      loss_sum = tf.Variable(0.0, name='loss_sum', trainable=False),
      accuracy_sum = tf.Variable(0.0, name='accuracy_sum', trainable=False))

def mnist_forward_pass(variables, batch):
  y = tf.nn.softmax(tf.matmul(batch['x'], variables.weights) + variables.bias)
  predictions = tf.cast(tf.argmax(y, 1), tf.int32)

  flat_labels = tf.reshape(batch['y'], [-1])
  loss = -tf.reduce_mean(tf.reduce_sum(
      tf.one_hot(flat_labels, 10) * tf.log(y), reduction_indices=[1]))
  accuracy = tf.reduce_mean(
      tf.cast(tf.equal(predictions, flat_labels), tf.float32))

  num_examples = tf.to_float(tf.size(batch['y']))

  tf.assign_add(variables.num_examples, num_examples)
  tf.assign_add(variables.loss_sum, loss * num_examples)
  tf.assign_add(variables.accuracy_sum, accuracy * num_examples)

  return loss, predictions

def get_local_mnist_metrics(variables):
  return collections.OrderedDict([
      ('num_examples', variables.num_examples),
      ('loss', variables.loss_sum / variables.num_examples),
      ('accuracy', variables.accuracy_sum / variables.num_examples)
    ])

@tff.federated_computation
def aggregate_mnist_metrics_across_clients(metrics):
  return {
      'num_examples': tff.federated_sum(metrics.num_examples),
      'loss': tff.federated_mean(metrics.loss, metrics.num_examples),
      'accuracy': tff.federated_mean(metrics.accuracy, metrics.num_examples)
  }

#Constructing an instance of tff.learning.Model
class MnistModel(tff.learning.Model):

  def __init__(self):
    self._variables = create_mnist_variables()

  @property
  def trainable_variables(self):
    return [self._variables.weights, self._variables.bias]

  @property
  def non_trainable_variables(self):
    return []

  @property
  def local_variables(self):
    return [
        self._variables.num_examples, self._variables.loss_sum,
        self._variables.accuracy_sum
    ]

  @property
  def input_spec(self):
    return collections.OrderedDict([('x', tf.TensorSpec([None, 784],
                                                        tf.float32)),
                                    ('y', tf.TensorSpec([None, 1], tf.int32))])

  @tf.contrib.eager.function(autograph=False)
  def forward_pass(self, batch, training=True):
    del training
    loss, predictions = mnist_forward_pass(self._variables, batch)
    return tff.learning.BatchOutput(loss=loss, predictions=predictions)

  @tf.contrib.eager.function(autograph=False)
  def report_local_outputs(self):
    return get_local_mnist_metrics(self._variables)

  @property
  def federated_output_computation(self):
    return aggregate_mnist_metrics_across_clients

class MnistTrainableModel(MnistModel, tff.learning.TrainableModel):
.
  @tf.contrib.eager.defun(autograph=False)
  def train_on_batch(self, batch):
    output = self.forward_pass(batch)
    optimizer = tf.train.GradientDescentOptimizer(0.02)
    optimizer.minimize(output.loss, var_list=self.trainable_variables)
    return output

if __name__=='__main__':
    iterative_process = tff.learning.build_federated_averaging_process(
        MnistTrainableModel)

**Comment by michaelreneer** [comment]
@INERKIDFYN You have two options here...
1. Run the colab that you linked from the latest release v0.2.0. https://github.com/tensorflow/federated/blob/v0.2.0/docs/tutorials/federated_learning_for_image_classification.ipynb
2. Build source at master, build a pip package, install the pip package, build a IPython kernel, and then run the notebook at master.

I would recommend option 1.

**Comment by INERKIDFYN** [comment]
@michaelreneer 
According to your suggestion 1, my problem has been solved. Thank you very much.

**Comment by TLGKien** [comment]
> m
hi. i'm trying option 1 and it informed me that: "module 'tensorflow_federated.python' has no attribute 'Computation'"
