### ISSUE TITLE
Error installing Tensorflow Federated with Python 3.9

### ISSUE THREAD

**Issue by zxj-c** [tensorflow/federated#4207]
Ran into the following error message 

Collecting numpy~=1.18.4 (from tensorflow-federated)
  Using cached numpy-1.18.5.zip (5.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      Running from numpy source directory.
      <string>:461: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      /private/var/folders/c7/9m1bsc9d0qz8dnmmnty3jgc00000gn/T/pip-install-fjzlbqdd/numpy_d4b9b1567fbe4f98b8b863467c8be452/tools/cythonize.py:75: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        required_version = LooseVersion('0.29.14')
      /private/var/folders/c7/9m1bsc9d0qz8dnmmnty3jgc00000gn/T/pip-install-fjzlbqdd/numpy_d4b9b1567fbe4f98b8b863467c8be452/tools/cythonize.py:77: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        if LooseVersion(cython_version) < required_version:
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  self.rng_state.ctr.v[i] = counter[i]
      
              self._reset_state_variables()
      
              self._bitgen.state = <void *>&self.rng_state
              self._bitgen.next_uint64 = &philox_uint64
                                         ^
      ------------------------------------------------------------
      
      _philox.pyx:195:35: Cannot assign type 'uint64_t (*)(void *) except? -1 nogil' to 'uint64_t (*)(void *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to type 'uint64_t (void *) except? -1 nogil'.
      Processing numpy/random/_bounded_integers.pxd.in
      Processing numpy/random/_philox.pyx
      Traceback (most recent call last):
        File "/private/var/folders/c7/9m1bsc9d0qz8dnmmnty3jgc00000gn/T/pip-install-fjzlbqdd/numpy_d4b9b1567fbe4f98b8b863467c8be452/tools/cythonize.py", line 238, in <module>
          main()
        File "/private/var/folders/c7/9m1bsc9d0qz8dnmmnty3jgc00000gn/T/pip-install-fjzlbqdd/numpy_d4b9b1567fbe4f98b8b863467c8be452/tools/cythonize.py", line 234, in main
          find_process_files(root_dir)
        File "/private/var/folders/c7/9m1bsc9d0qz8dnmmnty3jgc00000gn/T/pip-install-fjzlbqdd/numpy_d4b9b1567fbe4f98b8b863467c8be452/tools/cythonize.py", line 225, in find_process_files
          process(root_dir, fromfile, tofile, function, hash_db)
        File "/private/var/folders/c7/9m1bsc9d0qz8dnmmnty3jgc00000gn/T/pip-install-fjzlbqdd/numpy_d4b9b1567fbe4f98b8b863467c8be452/tools/cythonize.py", line 191, in process
          processor_function(fromfile, tofile)
        File "/private/var/folders/c7/9m1bsc9d0qz8dnmmnty3jgc00000gn/T/pip-install-fjzlbqdd/numpy_d4b9b1567fbe4f98b8b863467c8be452/tools/cythonize.py", line 80, in process_pyx
          subprocess.check_call(
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/Users/abc/Documents/GitHub/tff-dp-SecAgg/.venv/bin/python', '-m', 'cython', '-3', '--fast-fail', '-o', '_philox.c', '_philox.pyx']' returned non-zero exit status 1.
      Cythonizing sources
      Traceback (most recent call last):
        File "/Users/abc/Documents/GitHub/tff-dp-SecAgg/.venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/abc/Documents/GitHub/tff-dp-SecAgg/.venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/abc/Documents/GitHub/tff-dp-SecAgg/.venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/c7/9m1bsc9d0qz8dnmmnty3jgc00000gn/T/pip-build-env-j9vb0olx/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 396, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/c7/9m1bsc9d0qz8dnmmnty3jgc00000gn/T/pip-build-env-j9vb0olx/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/c7/9m1bsc9d0qz8dnmmnty3jgc00000gn/T/pip-build-env-j9vb0olx/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 488, in <module>
        File "<string>", line 469, in setup_package
        File "<string>", line 275, in generate_cython
      RuntimeError: Running cythonize failed!
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by zcharles8** [comment]
Can you fill in the details from the bug form? In particular, the environment info details, which I've reproduced below:

**Environment (please complete the following information):**
* OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
* Python package versions (e.g., TensorFlow Federated, TensorFlow):
* Python version:
* Bazel version (if building from source):
* CUDA/cuDNN version:
* What TensorFlow Federated execution stack are you using?

**Comment by stupidhhh** [comment]
> Can you fill in the details from the bug form? In particular, the environment info details, which I've reproduced below:
> 
> **Environment (please complete the following information):**
> 
> * OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
> * Python package versions (e.g., TensorFlow Federated, TensorFlow):
> * Python version:
> * Bazel version (if building from source):
> * CUDA/cuDNN version:
> * What TensorFlow Federated execution stack are you using?

excuse me, it is possible to use tensorflow-federated v0.63.0 on windows 11?

**Comment by zcharles8** [comment]
Unfortunately no, we do not support Windows at this time.

**Comment by stupidhhh** [comment]
> Unfortunately no, we do not support Windows at this time.

thinks
