### ISSUE TITLE
Issue of AssignAddVariableOp

### ISSUE THREAD

**Issue by AbbasiAYE** [tensorflow/federated#448]
Hello,

I'm using TFF, and I've been many errors. I tried to fix, but this error is a bit difficult. Your help is very much appreciated. I posted the code Traceback below, please let me know if I need to post other things.

Your help is most appreciated

Code:
======================================================
Outputs = tf.convert_to_tensor(np.random.rand(50,1))
        input1  = tf.convert_to_tensor(np.random.rand(50,100))
        Inputs  = input1
        
        Outputs = tf.cast(Outputs,tf.float32)
        Inputs = tf.cast(Inputs,tf.float32)
        new_batchInput = collections.OrderedDict([('In', Inputs),('Out', Outputs)])

        def generate_one_new_batch():
            yield new_batchInput
        
        dataset_input = tf.data.Dataset.from_tensor_slices(new_batchInput)#,outputs,maxval=100, dtype=tf.float32)
        dataset2 = dataset_input
        Used_dataset= dataset2
        
        def client_data(self,new_dataset):
            def map_fn(elem):
                #return collections.OrderedDict([('x', tf.reshape(elem['In'], [-1])),('y', tf.reshape(elem['Out'],[1]))])
                return collections.OrderedDict([('x', tf.reshape(elem['In'], [-1])),('y', tf.reshape(elem['Out'],[1]))])
            
            DS2= new_dataset.map(map_fn,num_parallel_calls=None)
            
            return DS2.repeat(10).batch(10)
        
        train_data = [client_data(self,Used_dataset)]

        sample_batch = tf.contrib.framework.nest.map_structure(lambda x: x.numpy(), next(iter(train_data[0])))

        def create_SK_model(learning_rate=0.1):
            
            modelF = tf.keras.Sequential([tf.keras.layers.Flatten(input_shape=(100,)),
                                         tf.keras.layers.Dense(10, activation=tf.nn.relu, kernel_initializer='zeros'),
                                         tf.keras.layers.Dense(1, activation=tf.nn.relu, kernel_initializer='zeros'),
                                         ])
            def loss_fn(y_true, y_pred):
                return tf.reduce_mean(tf.keras.losses.mse(y_true, y_pred))

            modelF.compile(loss=tf.keras.losses.mse,optimizer=gradient_descent.SGD(learning_rate))
            return modelF
        
           
        def model_fn():
            return tff.learning.from_compiled_keras_model(create_SK_model(0.1), sample_batch)
        
        YTrain = np.random.rand(50,1)
        XTrain = np.random.rand(50,100)
        
        create_SK_model(0.1).fit(XTrain,YTrain)
        
        trainer = tff.learning.build_federated_averaging_process(model_fn)
        state = trainer.initialize()
        losses = []
        for _ in range(2):
            state, outputs = trainer.next(state, train_data)
            # Track the loss.
            losses.append(outputs.loss)
                
        self.assertLess(losses[1], losses[0])

======================================================
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 1659, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shapes must be equal rank, but are 0 and 1 for 'AssignAddVariableOp' (op: 'AssignAddVariableOp') with input shapes: [], [?].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ezalaab\.p2\pool\plugins\org.python.pydev.core_7.1.0.201902031515\pysrc\pydevd.py", line 2225, in <module>
    main()
  File "C:\Users\ezalaab\.p2\pool\plugins\org.python.pydev.core_7.1.0.201902031515\pysrc\pydevd.py", line 2218, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Users\ezalaab\.p2\pool\plugins\org.python.pydev.core_7.1.0.201902031515\pysrc\pydevd.py", line 1560, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "C:\Users\ezalaab\.p2\pool\plugins\org.python.pydev.core_7.1.0.201902031515\pysrc\pydevd.py", line 1567, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\ezalaab\.p2\pool\plugins\org.python.pydev.core_7.1.0.201902031515\pysrc\_pydev_imps\_pydev_execfile.py", line 25, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\ezalaab\Documents\eclipse-workspace\MANA-FederatedLearning\location-based-federated-learning\Test\FLTF_models_test2.py", line 149, in <module>
    FLTest() 
  File "C:\Users\ezalaab\Documents\eclipse-workspace\MANA-FederatedLearning\location-based-federated-learning\Test\FLTF_models_test2.py", line 143, in __init__
    self.test_self_contained_example()
  File "C:\Users\ezalaab\Documents\eclipse-workspace\MANA-FederatedLearning\location-based-federated-learning\Test\FLTF_models_test2.py", line 125, in test_self_contained_example
    trainer = tff.learning.build_federated_averaging_process(model_fn)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_federated\python\learning\federated_averaging.py", line 148, in build_federated_averaging_process
    model_fn, client_fed_avg, server_optimizer_fn)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_federated\python\learning\framework\optimizer_utils.py", line 309, in build_model_delta_optimizer_process
    federated_dataset_type)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_federated\python\core\impl\computation_wrapper.py", line 408, in <lambda>
    return lambda fn: _wrap(fn, arg_type, self._wrapper_fn)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_federated\python\core\impl\computation_wrapper.py", line 96, in _wrap
    name=fn_name)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_federated\python\core\impl\computation_wrapper_instances.py", line 54, in _federated_computation_wrapper_fn
    suggested_name=name))
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_federated\python\core\impl\federated_computation_utils.py", line 75, in zero_or_one_arg_fn_to_building_block
    parameter_name, parameter_type), context_stack))
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_federated\python\core\impl\function_utils.py", line 553, in <lambda>
    return (lambda fn, at, kt: lambda arg: _unpack_and_call(fn, at, kt, arg))(
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_federated\python\core\impl\function_utils.py", line 547, in _unpack_and_call
    return fn(*args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_federated\python\learning\framework\optimizer_utils.py", line 323, in run_one_round_tff
    @tff.tf_computation(tf_dataset_type, model_weights_type)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_federated\python\core\impl\computation_wrapper.py", line 408, in <lambda>
    return lambda fn: _wrap(fn, arg_type, self._wrapper_fn)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_federated\python\core\impl\computation_wrapper.py", line 96, in _wrap
    name=fn_name)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_federated\python\core\impl\computation_wrapper_instances.py", line 38, in _tf_wrapper_fn
    target_fn, parameter_type, ctx_stack)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_federated\python\core\impl\tensorflow_serialization.py", line 92, in serialize_py_fn_as_tf_computation
    result = target(*args)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_federated\python\core\impl\function_utils.py", line 553, in <lambda>
    return (lambda fn, at, kt: lambda arg: _unpack_and_call(fn, at, kt, arg))(
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_federated\python\core\impl\function_utils.py", line 547, in _unpack_and_call
    return fn(*args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_federated\python\learning\framework\optimizer_utils.py", line 344, in client_delta_tf
    client_output = client_delta_fn(tf_dataset, initial_model_weights)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_federated\python\learning\federated_averaging.py", line 97, in __call__
    initial_state=tf.constant(0.0), reduce_func=reduce_fn)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 1224, in reduce
    add_to_graph=False)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 2129, in __init__
    self._function._create_definition_if_needed()  # pylint: disable=protected-access
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\function.py", line 341, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\function.py", line 355, in _create_definition_if_needed_impl
    whitelisted_stateful_ops=self._whitelisted_stateful_ops)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\function.py", line 883, in func_graph_from_py_func
    outputs = func(*func_graph.inputs)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 2099, in tf_data_structured_function_wrapper
    ret = func(*nested_args)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_federated\python\learning\federated_averaging.py", line 91, in reduce_fn
    output = model.train_on_batch(batch)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_federated\python\learning\model_utils.py", line 544, in train_on_batch
    self._model.train_on_batch(batch_input), model_lib.BatchOutput)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\eager\def_function.py", line 312, in __call__
    canon_args, canon_kwds = self._initialize(args, kwds)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\eager\def_function.py", line 280, in _initialize
    self._stateful_fn._get_concrete_function_internal(*args, **kwds))  # pylint: disable=protected-access
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\eager\function.py", line 876, in _get_concrete_function_internal
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\eager\function.py", line 1176, in _maybe_define_function
    arg_names=arg_names),
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\func_graph.py", line 448, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\eager\def_function.py", line 255, in wrapped_fn
    return wrapped_fn.__wrapped__(*args, **kwds)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\eager\function.py", line 1652, in bound_method_wrapper
    return wrapped_fn(weak_instance(), *args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_federated\python\learning\model_utils.py", line 451, in train_on_batch
    batch_output = self._forward_pass(batch_input)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_federated\python\learning\model_utils.py", line 382, in _forward_pass
    metric.update_state(y_true=y_true, y_pred=predictions)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\metrics.py", line 98, in decorated
    update_op = update_state_fn(*args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow_federated\python\learning\model_utils.py", line 321, in update_state
    op = self._total_loss.assign_add(batch_total_loss)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 881, in assign_add
    name=name)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\gen_resource_variable_ops.py", line 66, in assign_add_variable_op
    "AssignAddVariableOp", resource=resource, value=value, name=name)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\func_graph.py", line 281, in create_op
    compute_device=compute_device)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 1823, in __init__
    control_input_ops)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 1662, in _create_c_op
    raise ValueError(str(e))
ValueError: Shapes must be equal rank, but are 0 and 1 for 'AssignAddVariableOp' (op: 'AssignAddVariableOp') with input shapes: [], [?].

**Comment by ZacharyGarrett** [comment]
@AbbasiAYE 

It looks like when compiling the Keras model, the `tf.keras.losses.mse` function provided is not reducing the batch dimension ([API docs](https://www.tensorflow.org/api_docs/python/tf/keras/metrics/mean_squared_error?hl=en)). Just before compilation, the code defines a new method `loss_fn` that does the reduce. Could you try using this in the compile call?

When writing federated learning code, the recommendation is to start by writing only TF code (e.g. the Keras model) and ensuring the model can be trained and evaluated without any TFF.  Once that is working, wrap it with `tff.learning.from_compiled_keras_model()` and use it to build a federated learning process. Removing the TFF wrapping can also help in debugging where an error is occurring.

**Comment by AbbasiAYE** [comment]
Thanks @ZacharyGarrett 

I think you were right. If I remove the loss function, and NOT compile the model, then use tff.learning.from_keras_model (instead of from_compiled_keras_model) as a federated model in build_federated_averaging_process the process works fine. However, if I add any loss function and compile before passing to federated, then the same error occurs. BTW, as you suggested above, If i use the same loss function and compile/fit locally everything works fine. Any advice?

**Comment by ZacharyGarrett** [comment]
As mentioned previously, `tf.keras.losses.mse` is not reducing the batch dimension, which is necessary to compute a scalar loss (this is what `loss_fn` is doing). If I remember correctly, Keras will do this for you if you use `loss='mse'` or `loss=tf.keras.losses.MeanSquaredError()` when calling `compile()`.

It appears this is not a TFF issue, but a Keras usage issue so I'm going to close. If you're still having trouble, I'd recommended consulting the [tensorflow] and/or [keras] tags on StackOverflow.
