### ISSUE TITLE
cannot install v0.5.0

### ISSUE THREAD

**Issue by amitport** [tensorflow/federated#494]
that version is not in pypi and trying to install via `pip install -e git://github.com/tensorflow/federated.git@v0.5.0#egg=tensorflow_federated`

(seems to be missing root setup.py) (using windows)

produces 
```
Obtaining tensorflow_federated from git+git://github.com/tensorflow/federated.git@v0.5.0#egg=tensorflow_federated
  Cloning git://github.com/tensorflow/federated.git (to revision v0.5.0) to my-project\venv\src\tensorflow-federated
  Running command git clone -q git://github.com/tensorflow/federated.git 'my-project\venv\src\tensorflow-federated'
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\my-user\AppData\Local\Programs\Python\Python37\lib\tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: my-project\\venv\\src\\tensorflow-federated\\setup.py'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in my-project\venv\src\tensorflow-federated\
```

**Comment by amitport** [comment]
closing this as 0.5.0 was just published to pypi
