### ISSUE TITLE
Follow up on #258 TFF with BatchNormalization

### ISSUE THREAD

**Issue by AbbasiAYE** [tensorflow/federated#522]
Hello
I followed the discussion on #258 about keras models with batch_normalization, this is the relevant part of the code:

```
for round_num in range(2, 70): 
    FLstate, FLoutputs = trainer_Itr_Process.next(FLstate, federated_train_data)   
    FLlosses_arr.append(FLoutputs.loss)
    tff_weights= tff.learning.keras_weights_from_tff_weights(FLstate.model)
    tff_weights.assign_weights_to(tff_weights, Local_model_Fed)
```

I appreciate the help with the following error:

```
Traceback (most recent call last):
  File "C:\Users\ezalaab\.p2\pool\plugins\org.python.pydev.core_7.1.0.201902031515\pysrc\pydevd.py", line 2225, in <module>
    main()
  File "C:\Users\ezalaab\.p2\pool\plugins\org.python.pydev.core_7.1.0.201902031515\pysrc\pydevd.py", line 2218, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Users\ezalaab\.p2\pool\plugins\org.python.pydev.core_7.1.0.201902031515\pysrc\pydevd.py", line 1560, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "C:\Users\ezalaab\.p2\pool\plugins\org.python.pydev.core_7.1.0.201902031515\pysrc\pydevd.py", line 1567, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\ezalaab\.p2\pool\plugins\org.python.pydev.core_7.1.0.201902031515\pysrc\_pydev_imps\_pydev_execfile.py", line 25, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\ezalaab\Documents\eclipse-workspace\MANA-FederatedLearning\location-based-federated-learning\Test\FederatedLearningTFv3.py", line 299, in <module>
    tff_weights.assign_weights_to(tff_weights, Local_model_Fed)
AttributeError: 'list' object has no attribute 'assign_weights_to
```

**Comment by ZacharyGarrett** [comment]
I believe the code should skip the call to `tff.learning.keras_weights_from_tff_weights()`. Instead, just call `assign_weights_to()` from the `FLstate.model`. Something like:

```python
for round_num in range(2, 70): 
    FLstate, FLoutputs = trainer_Itr_Process.next(FLstate, federated_train_data)   
    FLlosses_arr.append(FLoutputs.loss)
    FLstate.model.assign_weights_to(Local_model_Fed)
```

This seems like it might be a better question for StackOverflow using the [tensorflow-federated] tag?

**Comment by AbbasiAYE** [comment]
Thanks for the response.

1. I have no idea how to differentiate between a question for StackOverflow or TFF forum.
2. At first I had problem with the installation, that is why the above error occurred. Then after fixing that, now I get another error as below:

Traceback (most recent call last):
```
  File "/home/abbasi/.eclipse/360744294_linux_gtk_x86_64/plugins/org.python.pydev.core_7.2.1.201904261721/pysrc/pydevd.py", line 2316, in <module>
    main()
  File "/home/abbasi/.eclipse/360744294_linux_gtk_x86_64/plugins/org.python.pydev.core_7.2.1.201904261721/pysrc/pydevd.py", line 2309, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/abbasi/.eclipse/360744294_linux_gtk_x86_64/plugins/org.python.pydev.core_7.2.1.201904261721/pysrc/pydevd.py", line 1642, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/home/abbasi/.eclipse/360744294_linux_gtk_x86_64/plugins/org.python.pydev.core_7.2.1.201904261721/pysrc/pydevd.py", line 1649, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/abbasi/.eclipse/360744294_linux_gtk_x86_64/plugins/org.python.pydev.core_7.2.1.201904261721/pysrc/_pydev_imps/_pydev_execfile.py", line 25, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/abbasi/eclipse-workspace/MANA/location-based-federated-learning/Test/FederatedLearningTFv3.py", line 298, in <module>
    FLstate.model.assign_weights_to(Local_model_Fed)
  File "/home/abbasi/.local/lib/python3.6/site-packages/tensorflow_federated/python/common_libs/anonymous_tuple.py", line 135, in __getattr__
    list(self._name_to_index.keys())[:10]))
AttributeError: The tuple of length 2 does not have named field "assign_weights_to".Names (only first 10): ['trainable', 'non_trainable']
```
Thanks for the support

**Comment by ZacharyGarrett** [comment]
For (1): its not always clear to us initially either, but its totally okay to move a question/issue from one to the other. Generally, questions about *how to use* TFF might better go on StackOverflow, especially when someone else may have the same question and would benefit from finding previous answers (preserved by StackOverflow). When a GitHub issue is closed, its not always easy to rediscover a solution. Otherwise, *issues with* TFF (e.g. running the vanilla colabs produces errors, feature requests, etc) probably are better as GitHub issues.

For (2): It looks like the code is still using `assign_weights_to()`. Could you try using `tff.learning.assign_weights_to_keras_model()`, as mentioned in the previous comment?

**Comment by AbbasiAYE** [comment]
Apologies for the lengthy discussion, now I'm using : 

```
# training/fitting with TF federated learning
trainer_Itr_Process = tff.learning.build_federated_averaging_process(model_fn_Federated,server_optimizer_fn=(lambda : gradient_descent.SGD(learning_rate=learn_rate)),client_weight_fn=None)
FLstate = trainer_Itr_Process.initialize()
FLlosses_arr  = []
Fed_eval_arr = []
# Track loss of different ...... of federated iteration
FLstate, FLoutputs = trainer_Itr_Process.next(FLstate, federated_train_data)   
# Track the loss.
FLlosses_arr.append(FLoutputs.loss)
# Setting federated weights on copied Object of local model
tff.learning.assign_weights_to_keras_model(FLstate.model,Local_model)
```

and got this error now:

```
Traceback (most recent call last):
  File "/home/abbasi/.eclipse/360744294_linux_gtk_x86_64/plugins/org.python.pydev.core_7.2.1.201904261721/pysrc/pydevd.py", line 2316, in <module>
    main()
  File "/home/abbasi/.eclipse/360744294_linux_gtk_x86_64/plugins/org.python.pydev.core_7.2.1.201904261721/pysrc/pydevd.py", line 2309, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/abbasi/.eclipse/360744294_linux_gtk_x86_64/plugins/org.python.pydev.core_7.2.1.201904261721/pysrc/pydevd.py", line 1642, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/home/abbasi/.eclipse/360744294_linux_gtk_x86_64/plugins/org.python.pydev.core_7.2.1.201904261721/pysrc/pydevd.py", line 1649, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/abbasi/.eclipse/360744294_linux_gtk_x86_64/plugins/org.python.pydev.core_7.2.1.201904261721/pysrc/_pydev_imps/_pydev_execfile.py", line 25, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/abbasi/eclipse-workspace/MANA/location-based-federated-learning/Test/FederatedLearningTFv3.py", line 299, in <module>
    tff.learning.assign_weights_to_keras_model(FLstate.model,Local_model)
  File "/home/abbasi/.local/lib/python3.6/site-packages/tensorflow_federated/python/learning/keras_utils.py", line 66, in assign_weights_to_keras_model
    tff_weights, (anonymous_tuple.AnonymousTuple, model_utils.ModelWeights))
  File "/home/abbasi/.local/lib/python3.6/site-packages/tensorflow_federated/python/common_libs/py_typecheck.py", line 48, in check_type
    type_string(type_spec), type_string(type(target))))
TypeError: Expected tensorflow_federated.python.common_libs.anonymous_tuple.AnonymousTuple or tensorflow_federated.python.learning.model_utils.ModelWeights, found tensorflow.python.keras.engine.sequential.Sequential.
```

I tracked the error it seems that in keras_utils have a problem with the tff.weights type, in the below function:

```
py_typecheck.check_type(
      tff_weights, (anonymous_tuple.AnonymousTuple, model_utils.ModelWeights))
```

I checked the type of tff_weights and model_utils.ModelWeights: 

```
>>> tff_weights
<tensorflow.python.keras.engine.sequential.Sequential object at 0x7f5438501eb8>
>>> model_utils.ModelWeights
<class 'tensorflow_federated.python.learning.model_utils.ModelWeights'>
```

Do you think its related to the definition of the model?

```
def create_SK_model():
        modelF = tf.keras.models.Sequential([tf.keras.layers.Dense(SNN_Layers[0],activation=tf.nn.relu,input_shape=(Act_Inputs.shape[1],), kernel_initializer='RandomNormal'),
                                      #tf.keras.layers.BatchNormalization(),
                                      tf.keras.layers.Dense(SNN_Layers[1], activation=tf.nn.relu, kernel_initializer='RandomNormal'),
                                      tf.keras.layers.Dropout(0.2),
                                      tf.keras.layers.Dense(1, activation=tf.nn.relu, kernel_initializer='RandomNormal'),
                                      ])
```

**Comment by ZacharyGarrett** [comment]
It looks like the code has the argument order flipped. `tff.learning.assign_weights_to_keras_model(keras_model, tff_weights)`  takes the local Keras model as the first argument, similar to the first code snippet I posted. The API docs are [here](https://www.tensorflow.org/federated/api_docs/python/tff/learning/assign_weights_to_keras_model).

Could you try flipping the order?

**Comment by AbbasiAYE** [comment]
Thanks a lot Zachary, I feel a shame for not identifying such basic error.
