### ISSUE TITLE
Unsuccessfully running tensorflow federated "Hello world" example

### ISSUE THREAD

**Issue by katarina-cavar** [tensorflow/federated#709]
Hello, 

I am trying to set up tensorflow federated environment on python 3.6, but can't manage to run the following recommended instruction from https://www.tensorflow.org/federated/install :
python3 -c "import tensorflow_federated as tff; tff.federated_computation(lambda: 'Hello World')()" 

The return message that I get is: 
WARNING: Logging before flag parsing goes to stderr.
W0719 10:34:39.394229 140431673673536 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

2019-07-19 10:34:39.827082: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-07-19 10:34:39.859038: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2494080000 Hz
2019-07-19 10:34:39.859594: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x49125d0 executing computations on platform Host. Devices:
2019-07-19 10:34:39.859632: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
Exception ignored in: <bound method _TensorCacheDeleter.__del__ of <tensorflow.python.eager.context._TensorCacheDeleter object at 0x7fb8a6fdd908>>
Traceback (most recent call last):
  File "/home/katarina/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/context.py", line 316, in __del__
TypeError: argument of type 'NoneType' is not iterable

After a while I've noticed that if I re-run the command "pip3 install tensorflow" the error changes. When I then re-run "pip3 install tensorflow_federated" again, the same error comes back. I've checked with "pip3 freeze" if any packages changed versions in between running the two commands, but all the packages stayed the same. 

In testing the behavior of the error, I was using the following two commands to tryout tensorflow and tensorflow_federated: 
1) python3 -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
2) python3 -c "import tensorflow_federated as tff; tff.federated_computation(lambda: 'Hello World')()"

#AFTER RUNNING "pip3 install tensorflow"
1)  python3 -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
Tensor("Sum:0", shape=(), dtype=float32)
(No error)

2) python3 -c "import tensorflow_federated as tff; tff.federated_computation(lambda: 'Hello World')()"

WARNING: Logging before flag parsing goes to stderr.
W0719 10:36:51.846138 140628469716800 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

2019-07-19 10:36:51.854925: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-07-19 10:36:51.878986: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2494080000 Hz
2019-07-19 10:36:51.879500: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x39654d0 executing computations on platform Host. Devices:
2019-07-19 10:36:51.879536: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>

#AFTER RUNNING "pip3 install tensorflow_federated"
1) python3 -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"

Tensor("Sum:0", shape=(), dtype=float32)
Exception ignored in: <bound method _TensorCacheDeleter.__del__ of <tensorflow.python.eager.context._TensorCacheDeleter object at 0x7f8709ca2eb8>>
Traceback (most recent call last):
  File "/home/katarina/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/context.py", line 316, in __del__
TypeError: argument of type 'NoneType' is not iterable

2) python3 -c "import tensorflow_federated as tff; tff.federated_computation(lambda: 'Hello World')()"

WARNING: Logging before flag parsing goes to stderr.
W0719 10:34:39.394229 140431673673536 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

2019-07-19 10:34:39.827082: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-07-19 10:34:39.859038: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2494080000 Hz
2019-07-19 10:34:39.859594: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x49125d0 executing computations on platform Host. Devices:
2019-07-19 10:34:39.859632: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
Exception ignored in: <bound method _TensorCacheDeleter.__del__ of <tensorflow.python.eager.context._TensorCacheDeleter object at 0x7fb8a6fdd908>>
Traceback (most recent call last):
  File "/home/katarina/.local/lib/python3.6/site-packages/tensorflow_core/python/eager/context.py", line 316, in __del__
TypeError: argument of type 'NoneType' is not iterable

I'm also attaching the list of packages installed 
[TFF_packages.txt](https://github.com/tensorflow/federated/files/3411247/TFF_packages.txt)

Thank you in advance! :)

**Comment by katarina-cavar** [comment]
Oops sorry for the ugly issue, I didn't realize it will get this ugly.
