### ISSUE TITLE
cannot import name 'computation_pb2'

### ISSUE THREAD

**Issue by phalangee** [tensorflow/federated#770]
I tried to connect pycharm to the remote server. The connection was successful. I used the virtual environment tff3. The jupyter remote connection to the virtual environment can make the code run successfully. However, the pycharm failed.
I created a new py file and entered the following statement. 
```
import tensorflow_federated as tff
print(tff.federateprint(tff.federated_computation(lambda: 'Hello World')()))
```
The error message is as follows:

```
ssh://liuxy@*.*.*.*:22/home/liuxy/anaconda3/envs/tff3/bin/python3 -u /home/liuxy/tmp/pycharm_project_567/docs/tutorials/image_classification.py
Traceback (most recent call last):
  File "/home/liuxy/tmp/pycharm_project_567/docs/tutorials/image_classification.py", line 1, in <module>
    import tensorflow_federated as tff
  File "/home/liuxy/tmp/pycharm_project_567/tensorflow_federated/__init__.py", line 23, in <module>
    from tensorflow_federated.python.core.api.computation_base import Computation
  File "/home/liuxy/tmp/pycharm_project_567/tensorflow_federated/python/core/__init__.py", line 21, in <module>
    from tensorflow_federated.python.core.api.computation_base import Computation
  File "/home/liuxy/tmp/pycharm_project_567/tensorflow_federated/python/core/api/__init__.py", line 29, in <module>
    from tensorflow_federated.python.core.api.computations import federated_computation
  File "/home/liuxy/tmp/pycharm_project_567/tensorflow_federated/python/core/api/computations.py", line 21, in <module>
    from tensorflow_federated.python.core.impl import computation_wrapper_instances
  File "/home/liuxy/tmp/pycharm_project_567/tensorflow_federated/python/core/impl/computation_wrapper_instances.py", line 22, in <module>
    from tensorflow_federated.python.core.impl import computation_impl
  File "/home/liuxy/tmp/pycharm_project_567/tensorflow_federated/python/core/impl/computation_impl.py", line 21, in <module>
    from tensorflow_federated.proto.v0 import computation_pb2 as pb
ImportError: cannot import name 'computation_pb2' from 'tensorflow_federated.proto.v0' (/home/liuxy/tmp/pycharm_project_567/tensorflow_federated/proto/v0/__init__.py)
```
Thank you very much

**Comment by jkr26** [comment]
Hi @phalangee 

We are familiar with this error; this is likely due to trying to launch or run the interpreter from within the same directory in which you have a copy of the source. If you move out of this directory, it should all work. This is because the Python interpreter is looking into the raw source of our `proto` files, which generate Python when TFF is compiled or run with `bazel`, but are not themselves Python.

**Comment by phalangee** [comment]
@jkr26  Thank you very much！  it worked for me !

**Comment by jkr26** [comment]
Awesome! Happy to help!
