### ISSUE TITLE
NotFoundError on import after pip install

### ISSUE THREAD

**Issue by jpgard** [tensorflow/federated#774]
I was using an older version of tff and tensorflow 1.x, but I am attempting to update to the newest version of tff and tensorflow 2.x.

I followed the pip installation instructions [here](https://github.com/tensorflow/federated/blob/master/docs/install.md#install-tensorflow-federated-using-pip), and set up and activated a virtual environment.  However, running the command in the optional step 4, to test tff, leads to the following output:

```
$ python -c "import tensorflow_federated as tff; print(tff.federated_computation(lambda: 'Hello World')())"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jpgard/Documents/github/federated/venv/lib/python3.6/site-packages/tensorflow_federated/__init__.py", line 62, in <module>
    from tensorflow_federated.python import simulation
  File "/Users/jpgard/Documents/github/federated/venv/lib/python3.6/site-packages/tensorflow_federated/python/simulation/__init__.py", line 23, in <module>
    from tensorflow_federated.python.simulation import datasets
  File "/Users/jpgard/Documents/github/federated/venv/lib/python3.6/site-packages/tensorflow_federated/python/simulation/datasets/__init__.py", line 21, in <module>
    from tensorflow_federated.python.simulation.datasets import emnist
  File "/Users/jpgard/Documents/github/federated/venv/lib/python3.6/site-packages/tensorflow_federated/python/simulation/datasets/emnist.py", line 29, in <module>
    import tensorflow_addons.image as tfa_image
  File "/Users/jpgard/Documents/github/federated/venv/lib/python3.6/site-packages/tensorflow_addons/__init__.py", line 21, in <module>
    from tensorflow_addons import activations
  File "/Users/jpgard/Documents/github/federated/venv/lib/python3.6/site-packages/tensorflow_addons/activations/__init__.py", line 21, in <module>
    from tensorflow_addons.activations.gelu import gelu
  File "/Users/jpgard/Documents/github/federated/venv/lib/python3.6/site-packages/tensorflow_addons/activations/gelu.py", line 25, in <module>
    get_path_to_datafile("custom_ops/activations/_activation_ops.so"))
  File "/Users/jpgard/Documents/github/federated/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/load_library.py", line 57, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: dlopen(/Users/jpgard/Documents/github/federated/venv/lib/python3.6/site-packages/tensorflow_addons/custom_ops/activations/_activation_ops.so, 6): Symbol not found: __ZN10tensorflow11GetNodeAttrERKNS_9AttrSliceEN4absl14lts_2019_08_0811string_viewEPb
  Referenced from: /Users/jpgard/Documents/github/federated/venv/lib/python3.6/site-packages/tensorflow_addons/custom_ops/activations/_activation_ops.so (which was built for Mac OS X 10.14)
  Expected in: /Users/jpgard/Documents/github/federated/venv/lib/python3.6/site-packages/tensorflow_core/python/../libtensorflow_framework.2.dylib
 in /Users/jpgard/Documents/github/federated/venv/lib/python3.6/site-packages/tensorflow_addons/custom_ops/activations/_activation_ops.so
```

If I comment out the dataset imports (`from tensorflow_federated.python.simulation.datasets import ...`) in tensorflow_federated.python.simulation.datasets.__init__.py`, the hello world command works fine.

Operating system: macOS High Sierra 10.13.6

Output of `pip freeze` inside venv:
```
absl-py==0.8.1
astor==0.8.0
attrs==18.2.0
cachetools==3.1.1
enum34==1.1.6
gast==0.2.2
google-pasta==0.1.7
grpcio==1.22.1
h5py==2.10.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
Markdown==3.1.1
mpmath==1.1.0
numpy==1.17.2
opt-einsum==3.1.0
portpicker==1.3.1
protobuf==3.10.0
scipy==1.3.1
six==1.12.0
tb-nightly==2.1.0a20191016
tensorflow-federated==0.9.0
tensorflow-model-optimization==0.1.3
tensorflow-privacy==0.1.0
termcolor==1.1.0
tf-estimator-nightly==2.0.0.dev2019101601
tf-nightly==2.1.0.dev20191015
tfa-nightly==0.7.0.dev20191010
Werkzeug==0.16.0
wrapt==1.11.2
```

**Comment by ZacharyGarrett** [comment]
Thank you for providing all the context, including the `pip freeze` output!

Commenting out datasets is likely to work because it stops pulling in the TensorFlow Addons (`tfa-nightly`) package, which is used for image transformations in the infinite EMNIST dataset.

For starters, could you try upgrading `tfa-nightly` package (`pip install --upgrade tfa-nightly`)? There looks to be a new package. We've seen similar problems with this package a few days ago, but internal continuous integration is passing this morning.

I also noticed the stack trace says `../_activation_ops.so` **`(which was built for Mac OS X 10.14)`**, but I believe the system is `10.13`? I'm not familiar with macOS, any idea if this might have some incompatibility?

**Comment by jpgard** [comment]
Hm, yes, the `tfa-nightly` seems to have been the issue -- no problem when rebuilding from a clean venv now. Thanks!
