### ISSUE TITLE
Distributed Demo

### ISSUE THREAD

**Issue by wangcaihua** [tensorflow/federated#775]
Hi, TFF team, i tred tff, and feel it cool. however, all the demos in tutorials are based on simulation data in one process (single machine of couse). do you have distributed demos? as you know, it is not difficult to simulate a cell in a standard alone process or docker container. i try this, but do not know how to do the communication between processes. i wish TFF team can help to build a distributed demo.

**Comment by ZacharyGarrett** [comment]
We're not quite there yet, early documentation for running on GCP is at https://github.com/tensorflow/federated/blob/master/docs/gcp_setup.md; but this still documents a single machine setup. Stay tuned.

**Comment by processdatatech** [comment]
same confusion , hope there is a example

**Comment by Dhrumilsoni** [comment]
@ZacharyGarrett 
Is it possible to run it distributed with the remote executor? 
(Something like this: [https://github.com/tensorflow/federated/blob/2d3ee312c489b2992a272bac59f5c28ef5d737c6/tensorflow_federated/python/examples/remote_executor_example.py])

I tried actually, but having trouble over communication via grpc.

**Comment by roselander** [comment]
@Dhrumilsoni it is definitely possible to run it in a distributed fashion. Please stay tuned for the next release of TFF in the next week or so, which will include a tutorial showing how to run TFF on Kubernetes using the RemoteExecutor. I also update this bug when the tutorial is available.

**Comment by jvmncs** [comment]
Is [this](https://github.com/tensorflow/federated/blob/master/tensorflow_federated/python/examples/remote_executor_example.py) that tutorial?

**Comment by roselander** [comment]
I'm presently working on a colab tutorial which includes instructions on how to start GKE instances, but this example may be helpful as well. I expect to have the tutorial up on the website in the next few days, and will update the bug when it's ready.

**Comment by roselander** [comment]
Actually the tutorial is public, we just haven't added it to the website yet: https://colab.research.google.com/github/tensorflow/federated/blob/master/docs/tutorials/high_performance_simulation_with_kubernetes.ipynb

For the {{version}} string in the docker image you should use "latest" for now. I just tested it, but please update this issue if you encounter any problems.

**Comment by petrovfedor** [comment]
Hey. Not sure if I should write it here. Is the demo still working with the latest Tensorflow release? I follow the steps and the execution just hangs when evaluate() is executed. Moreover, when I switched to the local execution, it says that there is no attribute loss in metrics in this line ````print('Round {}: loss {}, round time {}'.format(round, metrics.loss, t2 - t1))```` I checked and it works for ````metrics["train"]["loss"]```` but still not on Kubernetes cluster.

**Comment by SamuelGong** [comment]
> Hey. Not sure if I should write it here. Is the demo still working with the latest Tensorflow release? I follow the steps and the execution just hangs when evaluate() is executed. Moreover, when I switched to the local execution, it says that there is no attribute loss in metrics in this line `print('Round {}: loss {}, round time {}'.format(round, metrics.loss, t2 - t1))` I checked and it works for `metrics["train"]["loss"]` but still not on Kubernetes cluster.

Exactly same issue here after several months have passed... To be exact, for the above mentioned `the execution hang`, my version of **complete exception traceback** was like this for your reference:
```
/Users/xxx/anaconda3/lib/python3.7/site-packages/tensorflow_addons/utils/ensure_tf_install.py:43: UserWarning: You are currently using a nightly version of TensorFlow (2.5.0-dev20210218).                                                                                                                            
TensorFlow Addons offers no support for the nightly versions of TensorFlow. Some things might work, some other might not. 
If you encounter a bug, do not file an issue on GitHub.                                                                                                        UserWarning,                                                                
WARNING:tensorflow:Please add `keras.layers.InputLayer` instead of `keras.Input` to Sequential model. `keras.Input` is intended to be used by Functional model.                                                                                                                                                           
WARNING:tensorflow:Please add `keras.layers.InputLayer` instead of `keras.Input` to Sequential model. `keras.Input` is intended to be used by Functional model.
WARNING:tensorflow:Please add `keras.layers.InputLayer` instead of `keras.Input` to Sequential model. `keras.Input` is intended to be used by Functional model.
WARNING:tensorflow:Please add `keras.layers.InputLayer` instead of `keras.Input` to Sequential model. `keras.Input` is intended to be used by Functional model.
WARNING:tensorflow:Please add `keras.layers.InputLayer` instead of `keras.Input` to Sequential model. `keras.Input` is intended to be used by Functional model.
/Users/xxx/anaconda3/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executors/remote_executor.py:276: UserWarning: TFF streaming RPCs a
re deprecated and being removed; falling back to request-reply behavior.
  warnings.warn('TFF streaming RPCs are deprecated and being removed; '
Traceback (most recent call last):
  File "tff_with_k8s.py", line 43, in <module>
    evaluate()
  File "tff_with_k8s.py", line 33, in evaluate
    state, metrics = trainer.next(state, train_data)
  File "/Users/xxx/anaconda3/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/computation/function_utils.py", line 526, in __call__
    return context.invoke(self, arg)
  File "/Users/xxx/anaconda3/lib/python3.7/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/Users/xxx/anaconda3/lib/python3.7/site-packages/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "/Users/xxx/anaconda3/lib/python3.7/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/Users/xxx/anaconda3/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/Users/xxx/anaconda3/lib/python3.7/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/Users/xxx/anaconda3/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executors/execution_context.py", line 214, in invoke
with executor_closer(self._executor_factory, cardinalities) as executor:
  File "/Users/xxx/anaconda3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/Users/xxx/anaconda3/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executors/execution_context.py", line 204, in executor_closer
    raise e
  File "/Users/xxx/anaconda3/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executors/execution_context.py", line 201, in executor_closer
    yield ex_factory.create_executor(cardinalities)
  File "/Users/xxx/anaconda3/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executors/executor_stacks.py", line 850, in create_executor
    reconstructed = self._underlying_stack.create_executor(cardinalities)
  File "/Users/xxx/anaconda3/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executors/executor_stacks.py", line 518, in create_executor
    executors = self._flat_stack_fn(cardinalities)
  File "/Users/xxx/anaconda3/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executors/executor_stacks.py", line 1004, in _flat_stack_fn
    return _configure_remote_workers(num_clients, remote_executors)
  File "/Users/xxx/anaconda3/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executors/executor_stacks.py", line 933, in _configure_remo
te_workers
    ex, {placement_literals.CLIENTS: num_clients_to_host}, loop)
  File "/Users/xxx/anaconda3/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executors/executor_stacks.py", line 874, in _configure_remo
te_executor
    loop.run_until_complete(ex.set_cardinalities(cardinalities))
  File "/Users/xxx/anaconda3/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
return future.result()
  File "/Users/xxx/anaconda3/lib/python3.7/site-packages/tensorflow_federated/python/common_libs/tracing.py", line 201, in async_trace
    result = await fn(*fn_args, **fn_kwargs)
  File "/Users/xxx/anaconda3/lib/python3.7/sitepackages/tensorflow_federated/python/core/impl/executors/remote_executor.py", line 337, in set_cardinalities
    _request(self._stub.SetCardinalities, request)
  File "/Users/xxx/anaconda3/lib/python3.7/site-packages/tensorflow_federated/python/common_libs/tracing.py", line 228, in sync_trace
    result = fn(*fn_args, **fn_kwargs)
  File "/Users/xxx/anaconda3/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executors/remote_executor.py", line 214, in _request
    return rpc_func(request)
  File "/Users/xxx/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 923, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/xxx/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNIMPLEMENTED
        details = "Method not found!"
        debug_error_string = "{"created":"@1613705380.183300000","description":"Error received from peer ipv4:20.72.190.2:80","file":"src/core/lib/surface/ca
ll.cc","file_line":1063,"grpc_message":"Method not found!","grpc_status":12}"
>
```

I guess the reason behind is that the development of TF/TFF is undergoing fast innovations. I am thus, again, requesting for **up-to-date TFF with Kubernetes experience or verified demo**. Thanks!

**Comment by Ali-TRIPLab** [comment]
Hello guys, I also have the same problem running TFF on Kubernetes as explained in the tutorial here. High-performance Simulation with Kubernetes (https://colab.research.google.com/github/tensorflow/federated/blob/master/docs/tutorials/high_performance_simulation_with_kubernetes.ipynb#scrollTo=x5OhgAp7jrNI). Is there any update supposed to be published regarding the tutorial? Thanks!

**Comment by Ali-TRIPLab** [comment]
Hello guys, I also have the same problem running TFF on Kubernetes as explained in the tutorial here. High-performance Simulation with Kubernetes (https://colab.research.google.com/github/tensorflow/federated/blob/master/docs/tutorials/high_performance_simulation_with_kubernetes.ipynb#scrollTo=x5OhgAp7jrNI). Is there any update supposed to be published regarding the tutorial? Thanks!

**Comment by jeremygit** [comment]
Hello, not sure if this was resolved, but perhaps this might work.

Along with changing the line: `metrics["train"]["loss"]` in the client script, I also changed: `tff.simulation.run_server(executor_factory.create_executor({}), FLAGS.threads, FLAGS.port, credentials)` to `tff.simulation.run_server(executor_factory, FLAGS.threads, FLAGS.port, credentials)` of the remote_executor_service.py script within the Docker container. Using tff version 0.18.0...

`docker run -it gcr.io/tensorflow-federated/remote-executor-service:latest bash`

**Comment by dagoba-sermes-ai** [comment]
Hello everyone, 

I need your help. 

I try to run this example in K8s cluster. I'm using the deploy with 2 pods with PVC. The PVC have associate the path to "emnist_all.sqlite". I had use IP from Load Balancer and run the "execute()" function in my local laptop.

The "execute()" function return,

> grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
> 	status = StatusCode.INVALID_ARGUMENT
> 	details = "'329bf95e-e096-4aa0-8ed2-5a76fa53afbd'"
> 	debug_error_string = "{"created":"@1634208969.307600624","description":"Error received from peer ipv4:XX.XXX.XXX.XXX:80","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"'329bf95e-e096-4aa0-8ed2-5a76fa53afbd'","grpc_status":3}"


> Function call stack:
> pruned
> "
> 	debug_error_string = "{"created":"@1634209408.331193271","description":"Error received from peer ipv4:35.241.174.167:80","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Exception calling application:  Prepare() failed: [1] no such table: examples: SELECT serialized_example_proto FROM examples WHERE client_id = 'f0000_14' and split_name ='digits_only_train'\n\t [[{{node StatefulPartitionedCall_1/StatefulPartitionedCall/ReduceDataset}}]] [Op:__inference_pruned_16583]\n\nFunction call stack:\npruned\n","grpc_status":2}"

One of the pods returns nothing and the another returns,

> Function call stack:
> pruned
> 
> E1014 11:08:12.058994 139767136110336 _server.py:445] Exception calling application:  Prepare() failed: [1] no such table: examples: SELECT serialized_example_proto FROM examples WHERE client_id = 'f0001_41' and split_name ='digits_only_train'
>          [[{{node StatefulPartitionedCall_1/StatefulPartitionedCall/ReduceDataset}}]] [Op:__inference_pruned_20051]

> RuntimeError: The executor service has not yet been configured with cardinalities and cannot execute any concrete requests.
> 2021-10-14 11:08:22.303941: E tensorflow/core/framework/node_def_util.cc:623] NodeDef mentions attribute metadata which is not in the op definition: Op<name=ParallelMapDatasetV2; signature=input_dataset:variant, other_arguments:, num_parallel_calls:int64 -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=deterministic:string,default="default"; attr=preserve_cardinality:bool,default=false> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node ParallelMapDatasetV2/_5}}

Can you help me, please? Any idea?

Thanks in advance. Best,
