### ISSUE TITLE
Preprocessing error: TypeError: <lambda>() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by cianohagan** [tensorflow/federated#815]
Hi,

I am attempting the duplicate the EMNIST tutorial with another dataset by using tf.data to read data from tf keras image data generators. The issue arises when mapping the batch_format_fn to each batch of data as the mapping method passes 2 arguments to the batch_format_fn rather than the 1 'element' argument. I inspected the 2 arguments that are getting passed to the batch_format_fn and they were: 

```python
Tensor("args_0:0", dtype=float32)
Tensor("args_1:0", dtype=float32)
```

But when the same arguments are inspected when running the EMNIST example, it is one argument:

```python
OrderedDict([('label', <tf.Tensor 'args_0:0' shape=() dtype=int32>), ('pixels', <tf.Tensor 'args_1:0' shape=(28, 28) dtype=float32>)])
```

Below is the error:
```python
Traceback (most recent call last):
  File "src/federated_learning/federated_learning_model/model.py", line 189, in <module>
    prefetch_buffer
  File "src/federated_learning/federated_learning_model/model.py", line 47, in __init__
    prefetch_buffer)
  File "src/federated_learning/federated_learning_model/model.py", line 157, in _get_sample_batch
    revert_one_hot=False)
  File "/Users/cian.ohagan/Documents/federated_learning/project_repo/src/federated_learning/federated_learning_model/tff_utils.py", line 61, in preprocess
    mapped_dataset = shuffled_dataset.map(batch_format_fn)
  File "/Users/cian.ohagan/Documents/federated_learning/project_repo/fl_env/lib/python3.6/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 1588, in map
    return MapDataset(self, map_func, preserve_cardinality=True)
  File "/Users/cian.ohagan/Documents/federated_learning/project_repo/fl_env/lib/python3.6/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 3888, in __init__
    use_legacy_function=use_legacy_function)
  File "/Users/cian.ohagan/Documents/federated_learning/project_repo/fl_env/lib/python3.6/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 3147, in __init__
    self._function = wrapper_fn._get_concrete_function_internal()
  File "/Users/cian.ohagan/Documents/federated_learning/project_repo/fl_env/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2395, in _get_concrete_function_internal
    *args, **kwargs)
  File "/Users/cian.ohagan/Documents/federated_learning/project_repo/fl_env/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2389, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/Users/cian.ohagan/Documents/federated_learning/project_repo/fl_env/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2703, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/Users/cian.ohagan/Documents/federated_learning/project_repo/fl_env/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2593, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/Users/cian.ohagan/Documents/federated_learning/project_repo/fl_env/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 978, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/Users/cian.ohagan/Documents/federated_learning/project_repo/fl_env/lib/python3.6/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 3140, in wrapper_fn
    ret = _wrapper_helper(*args)
  File "/Users/cian.ohagan/Documents/federated_learning/project_repo/fl_env/lib/python3.6/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 3082, in _wrapper_helper
    ret = autograph.tf_convert(func, ag_ctx)(*nested_args)
  File "/Users/cian.ohagan/Documents/federated_learning/project_repo/fl_env/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py", line 237, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in converted code:


    TypeError: tf__batch_format_fn() takes 1 positional argument but 2 were given
```

The code below is extracted from the class that I am creating but has all the steps that are leading to the issue.

```python
    def read_client_data(path,
                         img_h,
                         img_w,
                        batch_size,
                        class_mode,
                        dataset='train'):
       path = os.path.join(path, dataset)


        def make_generator():
            train_datagen = image.ImageDataGenerator(rescale=1. / 255)
            train_generator = train_datagen.flow_from_directory(path,
                                                                target_size=[img_h, img_w],
                                                                class_mode=class_mode,
                                                                batch_size=batch_size)
            return train_generator

        train_dataset = tf.data.Dataset.from_generator(
            generator=make_generator,
            output_types=(tf.float32, tf.float32)
        )

        return train_dataset


    def batch_format_fn(element):
        """Flatten a batch `pixels` and return the features as an `OrderedDict`."""
        # batch = collections.OrderedDict(x=tf.reshape(element['pixels'], [-1, 784]),
        #                                 y=tf.reshape(element['label'], [-1, 1]))
        print('Running batch format ')
        print(element)
        batch = collections.OrderedDict(
            x=tf.reshape(element['pixels'], element['pixels'].shape),
            y=tf.reshape(element['label'], [-1, 1])
        )
        return batch


    def preprocess(dataset,
                   num_epochs,
                   shuffle_buffer,
                   batch_size,
                   prefetch_buffer,
                   revert_one_hot=False):
        # Repeating dataset count times
        repeated_dataset = dataset.repeat(count=num_epochs)
        # Randomly shuffling elements from dataset of size shuffle_buffer
        shuffled_dataset = repeated_dataset.shuffle(shuffle_buffer)
        # Combines consecutive elements of dataset into batches
        # Removed as the data is already in batches
        # batch = shuffled_dataset.batch(batch_size)
        # THE LINE BELOW THROWS THE ERROR
        mapped_dataset = shuffled_dataset.map(batch_format_fn)
        # mapped_dataset = shuffled_dataset.map(lambda self, x: batch_format_fn(x))
        if revert_one_hot:
            # Converting labels to ints
            mapped_dataset = mapped_dataset.map(lambda i, l: (i, tf.argmax(l, axis=1)))
        processed_dataset = mapped_dataset.prefetch(prefetch_buffer)
    return processed_dataset

    client_data = [read_client_data(os.path.join(path_to_data, client),
                                            self.img_h,
                                            self.img_w,
                                            self.batch_size,
                                            self.class_mode)
                              for client in clients]

    preprocessed_data = [preprocess(dataset,
                                            num_epochs,
                                            shuffle_buffer,
                                            batch_size,
                                            prefetch_buffer,
                                            revert_one_hot=False)
                                 for dataset in client_data]
```

**Comment by ZacharyGarrett** [comment]
The code in question is only using `tensorflow` core APIs (specifically setting up a `tf.data` pipeline), no `tensorflow_federated` or `tff` API. Looks like a usage question, rather than a issue/bug with Tensorflow Federated.

The best place for such questions is StackOverflow using the `tensorflow` tag (https://stackoverflow.com/questions/tagged/tensorflow). Could you re-post this question there?
