### ISSUE TITLE
Cannot run emnist_with_targeted_attack

### ISSUE THREAD

**Issue by anupamme** [tensorflow/federated#862]
**Describe the bug**
A clear and concise description of what the bug is. It is often helpful to
provide a link to a [colab](https://colab.research.google.com/) notebook that
reproduces the bug.

I tried running research code like this (after building the repo):

bazel run //tensorflow_federated/python/research/targeted_attack:emnist_with_targeted_attack

I get error in the following line:

path = tf.keras.utils.get_file(filename, url_malicious_dataset) (line 95 or 96)

The error details are:

Exception: URL fetch failure on https://storage.googleapis.com/tff-experiments-public/targeted_attack/emnist_test_data/emnist_test_data.mat: 403 -- Forbidden

It seems that the emnist data is not accessible (403 error). So perhaps we need to access it differently?

**Environment (please complete the following information):**
* OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
* Python package versions (e.g., TensorFlow Federated, TensorFlow):2.2.0, 0.14.0
* Python version: 3.6.9
* Bazel version (if building from source): 3.2.0
* CUDA/cuDNN version: 10.2
* What TensorFlow Federated execution stack are you using?

bazel run //tensorflow_federated/python/research/targeted_attack:emnist_with_targeted_attack

Note: You can collect the Python package information by running `pip3 freeze`
from the command line and most of the other information can be collected using
TensorFlows environment capture
[script](https://github.com/tensorflow/tensorflow/blob/master/tools/tf_env_collect.sh).

**Expected behavior**

I would expect the code in the emnist_with_targeted_attack to run.

**Additional context**

Even when I run this

wget https://storage.googleapis.com/tff-experiments-public/targeted_attack/emnist_test_data/emnist_test_data.mat

I get the same 403 error. So it looks like an accessibility issue.

**Comment by anupamme** [comment]
I moved the lines which load test data and malicious datasets to before the training loop begins to try to run remaining part of the code. I used the same command as above to run and I ran into following stack trace:

tensorflow.python.autograph.impl.api.StagingError: in user code:

    /home/anupam/.cache/bazel/_bazel_anupam/58ac23c114cd6a40a211d7004fec61ae/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/research/targeted_attack/emnist_with_targeted_attack.runfiles/org_tensorflow_federated/tensorflow_federated/python/research/targeted_attack/attacked_fedavg.py:590 __call__  *
        result = compute_malicious_update()
    /home/anupam/.cache/bazel/_bazel_anupam/58ac23c114cd6a40a211d7004fec61ae/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/research/targeted_attack/emnist_with_targeted_attack.runfiles/org_tensorflow_federated/tensorflow_federated/python/learning/model_utils.py:151 forward_pass  *
        self._model.forward_pass(batch_input, training), model_lib.BatchOutput)
    /home/anupam/.cache/bazel/_bazel_anupam/58ac23c114cd6a40a211d7004fec61ae/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/research/targeted_attack/emnist_with_targeted_attack.runfiles/org_tensorflow_federated/tensorflow_federated/python/learning/keras_utils.py:397 forward_pass  *
        return self._forward_pass(batch_input, training=training)
    /home/anupam/.cache/bazel/_bazel_anupam/58ac23c114cd6a40a211d7004fec61ae/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/research/targeted_attack/emnist_with_targeted_attack.runfiles/org_tensorflow_federated/tensorflow_federated/python/learning/keras_utils.py:363 _forward_pass  *
        raise KeyError('Received a batch_input that is missing required key `x`. '

    KeyError: "Received a batch_input that is missing required key `x`. Instead have keys ['label', 'pixels']"
> /home/anupam/.cache/bazel/_bazel_anupam/58ac23c114cd6a40a211d7004fec61ae/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/research/targeted_attack/emnist_with_targeted_attack.runfiles/org_tensorflow_federated/tensorflow_federated/python/research/targeted_attack/emnist_with_targeted_attack.py(268)main()
-> server_optimizer_fn=server_optimizer_fn)


This is a different issue technically so I can open another issue but since it is related to running emnist_with_targeted_attack, I thought I will add it in the already open issue. So let me know if you would prefer to open another issue.

**Comment by zcharles8** [comment]
Hi @anupamme, and thanks for letting us know about the bugs you encountered. I just pushed [this commit](https://github.com/tensorflow/federated/commit/fb95ef827e20eab77b41c09c8fff9312e38d6247) which should resolve the issue. Please let me know if this fixes the problem for you.

**Comment by anupamme** [comment]
Hello

Yes, the issues are fixed and I can run the code now. Thanks!

**Comment by anupamme** [comment]
Hello,

I believe with the latest checkins, something has broken and I am not able to run targeted_attack/emnist_with_targeted_attack.py.

The errors are these:

1. In targeted_attack/emnist_with_targeted_attack: 302, type(train_metrics) is OrderedDict so you cannot index it. 

2. I fixed this in my local by: list(train_metrics.values()), however then I ran into another type issue:

Traceback (most recent call last):
  File "/home/anupam/.cache/bazel/_bazel_anupam/be23b43dd262b601d703273297e13e7b/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/research/targeted_attack/emnist_with_targeted_attack.runfiles/org_tensorflow_federated/tensorflow_federated/python/research/targeted_attack/emnist_with_targeted_attack.py", line 329, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/anupam/.cache/bazel/_bazel_anupam/be23b43dd262b601d703273297e13e7b/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/research/targeted_attack/emnist_with_targeted_attack.runfiles/org_tensorflow_federated/tensorflow_federated/python/research/targeted_attack/emnist_with_targeted_attack.py", line 311, in main
    target_y)
  File "/home/anupam/.cache/bazel/_bazel_anupam/be23b43dd262b601d703273297e13e7b/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/research/targeted_attack/emnist_with_targeted_attack.runfiles/org_tensorflow_federated/tensorflow_federated/python/research/targeted_attack/emnist_with_targeted_attack.py", line 176, in evaluate
    tff.learning.assign_weights_to_keras_model(keras_model, state.model)
  File "/home/anupam/.cache/bazel/_bazel_anupam/be23b43dd262b601d703273297e13e7b/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/research/targeted_attack/emnist_with_targeted_attack.runfiles/org_tensorflow_federated/tensorflow_federated/python/learning/keras_utils.py", line 58, in assign_weights_to_keras_model
    tff_weights, (anonymous_tuple.AnonymousTuple, model_utils.ModelWeights))
  File "/home/anupam/.cache/bazel/_bazel_anupam/be23b43dd262b601d703273297e13e7b/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/research/targeted_attack/emnist_with_targeted_attack.runfiles/org_tensorflow_federated/tensorflow_federated/python/common_libs/py_typecheck.py", line 41, in check_type
    type_string(type_spec), type_string(type(target))))
TypeError: Expected tensorflow_federated.python.common_libs.anonymous_tuple.AnonymousTuple or tensorflow_federated.python.learning.model_utils.ModelWeights, found tensorflow.python.autograph.impl.api.ModelWeights.
