### ISSUE TITLE
Got error when run personalization experiment

### ISSUE THREAD

**Issue by ddayzzz** [tensorflow/federated#892]
**Describe the bug**
A clear and concise description of what the bug is. It is often helpful to
provide a link to a [colab](https://colab.research.google.com/) notebook that
reproduces the bug.

**Environment (please complete the following information):**
* OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
* Python package versions (e.g., TensorFlow Federated, TensorFlow): Tensoflow-gpu 2.2, federated 0.16.1(From pypi)
* CUDA/cuDNN version: 10.1
I tried to run personalization experiment unittest but I got some errors. [https://github.com/tensorflow/federated/blob/993493122ea908173eba68525482d5d522db236c/tensorflow_federated/python/research/personalization/p13n_utils_test.py](https://github.com/tensorflow/federated/blob/993493122ea908173eba68525482d5d522db236c/tensorflow_federated/python/research/personalization/p13n_utils_test.py#L1)

```
Testing started at 0:33 ...
ssh://liuyuan@122.207.82.54:14000/home/liuyuan/programs/miniconda3/envs/tf2/bin/python -u /home/liuyuan/.pycharm_helpers/pycharm/_jb_unittest_runner.py --target p13n_utils_test.P13NUtilsTest.test_build_personalize_fn_succeeds_with_valid_args
Launching unittests with arguments python -m unittest p13n_utils_test.P13NUtilsTest.test_build_personalize_fn_succeeds_with_valid_args in /home/liuyuan/shu_codes/federated_learning_tff/personalization

2020-08-13 00:33:25.201227: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-08-13 00:33:33.437511: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:1a:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.545GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2020-08-13 00:33:33.437864: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-08-13 00:33:33.440622: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-08-13 00:33:33.443281: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-08-13 00:33:33.443706: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-08-13 00:33:33.446540: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-08-13 00:33:33.448197: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-08-13 00:33:33.454645: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-08-13 00:33:33.456487: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-08-13 00:33:33.458319: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
2020-08-13 00:33:33.505750: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2100000000 Hz
2020-08-13 00:33:33.510571: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55d7f3df9770 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-13 00:33:33.510589: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-08-13 00:33:33.511533: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:1a:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.545GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2020-08-13 00:33:33.511581: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-08-13 00:33:33.511598: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-08-13 00:33:33.511614: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-08-13 00:33:33.511631: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-08-13 00:33:33.511647: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-08-13 00:33:33.511663: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-08-13 00:33:33.511680: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-08-13 00:33:33.513154: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-08-13 00:33:33.513194: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-08-13 00:33:33.624360: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-08-13 00:33:33.624391: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-08-13 00:33:33.624397: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-08-13 00:33:33.626161: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10203 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:1a:00.0, compute capability: 7.5)
2020-08-13 00:33:33.628552: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55d7f7d467b0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-08-13 00:33:33.628570: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
/home/liuyuan/programs/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/training/tracking/data_structures.py:718: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  if not isinstance(wrapped_dict, collections.Mapping):
WARNING:tensorflow:From /home/liuyuan/programs/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:1666: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.

Error
Traceback (most recent call last):
  File "/home/liuyuan/programs/miniconda3/envs/tf2/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/home/liuyuan/programs/miniconda3/envs/tf2/lib/python3.7/unittest/case.py", line 628, in run
    testMethod()
  File "/home/liuyuan/shu_codes/federated_learning_tff/personalization/p13n_utils_test.py", line 71, in test_build_personalize_fn_succeeds_with_valid_args
    p13n_metrics = p13n_fn(model=model, train_data=dataset, test_data=dataset)
  File "/home/liuyuan/programs/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/home/liuyuan/programs/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 644, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/liuyuan/programs/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2420, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/liuyuan/programs/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1665, in _filtered_call
    self.captured_inputs)
  File "/home/liuyuan/programs/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1746, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/liuyuan/programs/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 598, in call
    ctx=ctx)
  File "/home/liuyuan/programs/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal:  No unary variant device copy function found for direction: 1 and Variant type_index: tensorflow::data::(anonymous namespace)::DatasetVariantWrapper
	 [[{{node test_data/_32}}]]
	 [[Func/while/body/_11/input/_134/_52]]
  (1) Internal:  No unary variant device copy function found for direction: 1 and Variant type_index: tensorflow::data::(anonymous namespace)::DatasetVariantWrapper
	 [[{{node test_data/_32}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference_personalize_fn_1025]

Function call stack:
personalize_fn -> personalize_fn
```

**Comment by nightldj** [comment]
@ddayzzz Could you update TF to 2.3 to see if the error still exists? Thanks!

**Comment by ddayzzz** [comment]
> @ddayzzz Could you update TF to 2.3 to see if the error still exists? Thanks!

I upgrade tensorflow(gpu version) to 2.3 from pypi, but i still got the same errors.
```
Launching unittests with arguments python -m unittest p13n_utils_test.P13NUtilsTest.test_build_personalize_fn_succeeds_with_valid_args in /home/liuyuan/shu_codes/federated_learning_tff/personalization

2020-08-15 18:30:48.587939: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
/home/liuyuan/programs/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_addons/utils/ensure_tf_install.py:68: UserWarning: Tensorflow Addons supports using Python ops for all Tensorflow versions above or equal to 2.2.0 and strictly below 2.3.0 (nightly versions are not supported). 
 The versions of TensorFlow you are currently using is 2.3.0 and is not supported. 
Some things might work, some things might not.
If you were to encounter a bug, do not file an issue.
If you want to make sure you're using a tested and supported configuration, either change the TensorFlow version or the TensorFlow Addons's version. 
You can find the compatibility matrix in TensorFlow Addon's readme:
https://github.com/tensorflow/addons
  UserWarning,
2020-08-15 18:30:49.779733: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-08-15 18:30:57.406770: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:b2:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.545GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2020-08-15 18:30:57.406905: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-08-15 18:30:57.412322: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-08-15 18:30:57.415537: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-08-15 18:30:57.415976: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-08-15 18:30:57.418986: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-08-15 18:30:57.420530: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2020-08-15 18:30:57.426628: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-08-15 18:30:57.428847: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-08-15 18:30:57.430272: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-08-15 18:30:57.478005: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2100000000 Hz
2020-08-15 18:30:57.486456: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x56144dbf0470 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-15 18:30:57.486533: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-08-15 18:30:57.637296: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x56144fcc6590 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-08-15 18:30:57.637361: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
2020-08-15 18:30:57.640469: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:b2:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.545GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2020-08-15 18:30:57.640593: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-08-15 18:30:57.640646: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-08-15 18:30:57.640677: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-08-15 18:30:57.640707: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-08-15 18:30:57.640737: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-08-15 18:30:57.640766: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2020-08-15 18:30:57.640797: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-08-15 18:30:57.644716: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-08-15 18:30:57.644789: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-08-15 18:30:58.383153: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-08-15 18:30:58.383202: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 
2020-08-15 18:30:58.383211: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N 
2020-08-15 18:30:58.384784: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10066 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:b2:00.0, compute capability: 7.5)

Error
Traceback (most recent call last):
  File "/home/liuyuan/programs/miniconda3/envs/tf2/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/home/liuyuan/programs/miniconda3/envs/tf2/lib/python3.7/unittest/case.py", line 628, in run
    testMethod()
  File "/home/liuyuan/shu_codes/federated_learning_tff/personalization/p13n_utils_test.py", line 75, in test_build_personalize_fn_succeeds_with_valid_args
    loop()
  File "/home/liuyuan/programs/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/home/liuyuan/programs/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 846, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "/home/liuyuan/programs/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/home/liuyuan/programs/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/liuyuan/programs/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/home/liuyuan/programs/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal:  No unary variant device copy function found for direction: 1 and Variant type_index: tensorflow::data::(anonymous namespace)::DatasetVariantWrapper
	 [[{{node BatchDatasetV2/_18}}]]
  (1) Internal:  No unary variant device copy function found for direction: 1 and Variant type_index: tensorflow::data::(anonymous namespace)::DatasetVariantWrapper
	 [[{{node BatchDatasetV2/_18}}]]
	 [[Func/while/body/_1/input/_51/_46]]
0 successful operations.
0 derived errors ignored. [Op:__inference_loop_85]

Function call stack:
loop -> loop



Assertion failed


Ran 1 test in 9.051s

FAILED (errors=1)

Process finished with exit code 1

Assertion failed

Assertion failed

```

**Comment by nightldj** [comment]
@ddayzzz Sorry that you still hit the issue. Could you try tf-nightly if possible? We cannot currently reproduce the issue, but I think I have seen it before. It is a bug inherited from TF on GPUs, and the bug has been fixed in TF. I am not sure if the fix has been in the released version yet, but TF-nightly should be good.

**Comment by ddayzzz** [comment]
> @ddayzzz Sorry that you still hit the issue. Could you try tf-nightly if possible? We cannot currently reproduce the issue, but I think I have seen it before. It is a bug inherited from TF on GPUs, and the bug has been fixed in TF. I am not sure if the fix has been in the released version yet, but TF-nightly should be good.

Install `tf-nightly` or `tf-nightly-gpu` ?

**Comment by ddayzzz** [comment]
> @ddayzzz Sorry that you still hit the issue. Could you try tf-nightly if possible? We cannot currently reproduce the issue, but I think I have seen it before. It is a bug inherited from TF on GPUs, and the bug has been fixed in TF. I am not sure if the fix has been in the released version yet, but TF-nightly should be good.

Thank you. tensorflow-federated works properly under tf 2.3.0 and tf-nightly.

**Comment by ddayzzz** [comment]
But when I run personalization experiment [run_emnist_p13n.py](https://github.com/tensorflow/federated/blob/6e93818b22748747508faa5c7b6313a1920e079a/tensorflow_federated/python/research/personalization/run_emnist_p13n.py#L209). There is no output(very slow).

```
ssh://liuyuan@122.207.82.54:14000/home/liuyuan/programs/miniconda3/envs/tf2/bin/python -u /home/liuyuan/shu_codes/federated_learning_tff/ori/run_emnist_p13n.py
2020-08-16 15:36:23.666519: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
/home/liuyuan/programs/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_addons/utils/ensure_tf_install.py:68: UserWarning: Tensorflow Addons supports using Python ops for all Tensorflow versions above or equal to 2.2.0 and strictly below 2.3.0 (nightly versions are not supported). 
 The versions of TensorFlow you are currently using is 2.3.0 and is not supported. 
Some things might work, some things might not.
If you were to encounter a bug, do not file an issue.
If you want to make sure you're using a tested and supported configuration, either change the TensorFlow version or the TensorFlow Addons's version. 
You can find the compatibility matrix in TensorFlow Addon's readme:
https://github.com/tensorflow/addons
  UserWarning,
2020-08-16 15:36:37.875259: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-08-16 15:36:47.157134: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:b2:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.545GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2020-08-16 15:36:47.157232: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-08-16 15:36:47.161043: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-08-16 15:36:47.164504: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-08-16 15:36:47.165125: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-08-16 15:36:47.167947: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-08-16 15:36:47.169182: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2020-08-16 15:36:47.174922: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-08-16 15:36:47.177007: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-08-16 15:36:47.178262: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-08-16 15:36:47.230059: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2100000000 Hz
2020-08-16 15:36:47.239795: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x561af830a790 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-16 15:36:47.239849: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-08-16 15:36:47.440497: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x561af5dafbf0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-08-16 15:36:47.440543: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
2020-08-16 15:36:47.441917: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:b2:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.545GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2020-08-16 15:36:47.441977: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-08-16 15:36:47.442011: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-08-16 15:36:47.442028: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-08-16 15:36:47.442046: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-08-16 15:36:47.442067: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-08-16 15:36:47.442084: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2020-08-16 15:36:47.442101: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-08-16 15:36:47.444195: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-08-16 15:36:47.444247: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-08-16 15:36:48.072469: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-08-16 15:36:48.072517: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 
2020-08-16 15:36:48.072524: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N 
2020-08-16 15:36:48.074108: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10066 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:b2:00.0, compute capability: 7.5)
2020-08-16 15:37:29.833473: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-08-16 15:37:30.196852: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-08-16 15:37:31.593474: W tensorflow/stream_executor/gpu/asm_compiler.cc:116] *** WARNING *** You are using ptxas 9.1.108, which is older than 9.2.88. ptxas 9.x before 9.2.88 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You do not need to update to CUDA 9.2.88; cherry-picking the ptxas binary is sufficient.
2020-08-16 15:37:31.870552: W tensorflow/stream_executor/gpu/redzone_allocator.cc:314] Internal: ptxas exited with non-zero error code 65280, output: ptxas fatal   : Value 'sm_75' is not defined for option 'gpu-name'

Relying on driver to perform ptx compilation. 
Modify $PATH to customize ptxas location.
This message will be only logged once.

```
