### ISSUE TITLE
"TypeError: Unable to convert a Python object of type numpy.float32 into an `Struct`. Object: 5.0" when running emnist_with_targeted_attack.py

### ISSUE THREAD

**Issue by DemoAllan** [tensorflow/federated#909]
**Describe the bug**
Hello, there's something wrong when I run emnist_with_targeted_attack.py. First I downloaded the datasets used in the code from the urls because I cannot get them directly when I run the code. Then I used `python emnist_with_targeted_attack.py` to run the code from the cmd (anaconda virtual environment about TF 2.2), and I got the following error messages:

Skipping registering GPU devices...
2020-09-15 14:39:37.981377: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-09-15 14:39:37.996552: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2411ecb8180 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-15 14:39:38.006755: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-09-15 14:39:38.017073: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-15 14:39:38.023607: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]
=======configurations========
random_seed=0-num_clients_per_round=5-num_rounds=300-server_learning_rate=1.0-num_epochs=5-batch_size=20-client_learning_rate=0.1-client_round_num=5-attack_freq=1-task_num=30-drop_prob=0.5-norm_bound=0.33-l2_norm_clip=1.0-mul_factor=0.0
=======configurations========
Loading Dataset!
Loading Test Set!
Loading malicious dataset!
Building Iterative Process!
WARNING:tensorflow:From D:\install\anaconda\envs\tensorflow2\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py:1659: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
W0915 14:39:48.087962 15780 deprecation.py:500] From D:\install\anaconda\envs\tensorflow2\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py:1659: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Attacker appears!
Round starts!
Traceback (most recent call last):
  File "D:\install\anaconda\envs\tensorflow2\lib\site-packages\tensorflow_federated\python\core\impl\executors\caching_executor.py", line 63, in _get_hashable_key
    value = structure.from_container(value)
  File "D:\install\anaconda\envs\tensorflow2\lib\site-packages\tensorflow_federated\python\common_libs\structure.py", line 488, in from_container
    return _convert(value, recursive, must_be_container=True)
  File "D:\install\anaconda\envs\tensorflow2\lib\site-packages\tensorflow_federated\python\common_libs\structure.py", line 482, in _convert
    raise TypeError('Unable to convert a Python object of type {} into '
TypeError: Unable to convert a Python object of type numpy.float32 into an `Struct`. Object: 5.0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "emnist_with_targeted_attack.py", line 327, in <module>
    app.run(main)
  File "D:\install\anaconda\envs\tensorflow2\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "D:\install\anaconda\envs\tensorflow2\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "emnist_with_targeted_attack.py", line 293, in main
    state, train_metrics = iterative_process.next(state, federated_train_data,
  File "D:\install\anaconda\envs\tensorflow2\lib\site-packages\tensorflow_federated\python\core\impl\utils\function_utils.py", line 561, in __call__
    return context.invoke(self, arg)
  File "D:\install\anaconda\envs\tensorflow2\lib\site-packages\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "D:\install\anaconda\envs\tensorflow2\lib\site-packages\retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "D:\install\anaconda\envs\tensorflow2\lib\site-packages\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "D:\install\anaconda\envs\tensorflow2\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "D:\install\anaconda\envs\tensorflow2\lib\site-packages\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "D:\install\anaconda\envs\tensorflow2\lib\site-packages\tensorflow_federated\python\core\impl\executors\execution_context.py", line 211, in invoke
    arg = event_loop.run_until_complete(
  File "D:\install\anaconda\envs\tensorflow2\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "D:\install\anaconda\envs\tensorflow2\lib\site-packages\tensorflow_federated\python\common_libs\tracing.py", line 388, in _wrapped
    return await coro
  File "D:\install\anaconda\envs\tensorflow2\lib\site-packages\tensorflow_federated\python\core\impl\executors\execution_context.py", line 98, in _ingest
    ingested = await asyncio.gather(*ingested)
  File "D:\install\anaconda\envs\tensorflow2\lib\site-packages\tensorflow_federated\python\core\impl\executors\execution_context.py", line 103, in _ingest
    return await executor.create_value(val, type_spec)
  File "D:\install\anaconda\envs\tensorflow2\lib\site-packages\tensorflow_federated\python\common_libs\tracing.py", line 200, in async_trace
    result = await fn(*fn_args, **fn_kwargs)
  File "D:\install\anaconda\envs\tensorflow2\lib\site-packages\tensorflow_federated\python\core\impl\executors\reference_resolving_executor.py", line 286, in create_value
    return ReferenceResolvingExecutorValue(await
  File "D:\install\anaconda\envs\tensorflow2\lib\site-packages\tensorflow_federated\python\core\impl\executors\caching_executor.py", line 214, in create_value
    hashable_key = _get_hashable_key(value, type_spec)
  File "D:\install\anaconda\envs\tensorflow2\lib\site-packages\tensorflow_federated\python\core\impl\executors\caching_executor.py", line 75, in _get_hashable_key
    return _get_hashable_key(value, type_spec.member)
  File "D:\install\anaconda\envs\tensorflow2\lib\site-packages\tensorflow_federated\python\core\impl\executors\caching_executor.py", line 71, in _get_hashable_key
    r_elem.append((field_name, _get_hashable_key(v, field_type)))
  File "D:\install\anaconda\envs\tensorflow2\lib\site-packages\tensorflow_federated\python\core\impl\executors\caching_executor.py", line 71, in _get_hashable_key
    r_elem.append((field_name, _get_hashable_key(v, field_type)))
  File "D:\install\anaconda\envs\tensorflow2\lib\site-packages\tensorflow_federated\python\core\impl\executors\caching_executor.py", line 65, in _get_hashable_key
    raise TypeError(
TypeError: Failed to convert value with type_spec StructType([('l2_norm_clip', TensorType(tf.float32)), ('stddev', TensorType(tf.float32))]) as _GlobalState to `Struct`
E0915 14:40:02.875965 15780 base_events.py:1707] Task was destroyed but it is pending!
task: <Task pending name='Task-109' coro=<trace.<locals>.async_trace() running at D:\install\anaconda\envs\tensorflow2\lib\site-packages\tensorflow_federated\python\common_libs\tracing.py:200> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at D:\install\anaconda\envs\tensorflow2\lib\asyncio\futures.py:360, <TaskWakeupMethWrapper object at 0x00000241317C98B0>()]> cb=[<TaskWakeupMethWrapper object at 0x0000024132398670>()]>
E0915 14:40:02.876966 15780 base_events.py:1707] Task was destroyed but it is pending!
task: <Task pending name='Task-110' coro=<trace.<locals>.async_trace() running at D:\install\anaconda\envs\tensorflow2\lib\site-packages\tensorflow_federated\python\common_libs\tracing.py:200> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at D:\install\anaconda\envs\tensorflow2\lib\asyncio\futures.py:360, <TaskWakeupMethWrapper object at 0x00000241317C59A0>()]> cb=[<TaskWakeupMethWrapper object at 0x0000024132398730>()]>
E0915 14:40:02.879963 15780 base_events.py:1707] Task was destroyed but it is pending!
task: <Task pending name='Task-111' coro=<trace.<locals>.async_trace() running at D:\install\anaconda\envs\tensorflow2\lib\site-packages\tensorflow_federated\python\common_libs\tracing.py:200> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at D:\install\anaconda\envs\tensorflow2\lib\asyncio\futures.py:360, <TaskWakeupMethWrapper object at 0x00000241317C55E0>()]> cb=[<TaskWakeupMethWrapper object at 0x0000024132398D30>()]>

**Environment (please complete the following information):**
* OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows10
* Python package versions (e.g., TensorFlow Federated, TensorFlow): TF 2.2.0; TFF 0.16.1
* Python version: python 3.8
* Bazel version (if building from source): No
* CUDA/cuDNN version: No
* What TensorFlow Federated execution stack are you using? cmd

Note: You can collect the Python package information by running `pip3 freeze`
from the command line and most of the other information can be collected using
TensorFlows environment capture
[script](https://github.com/tensorflow/tensorflow/blob/master/tools/tf_env_collect.sh).

**Expected behavior**
I want to run emnist_with_targeted_attack.py correctly.

**Comment by DemoAllan** [comment]
After debugging the code for 5 hours, I can finally run this code under TFF 0.15.0.
The emnist_with_targeted_attack.py is written under the environment of TF 2.x and TFF 0.15.0, so I degrade the TFF.
Also there's an another question I want to ask: How can I get every  Clients' updated weights of each iterations? Is there any api to use?

**Comment by ZacharyGarrett** [comment]
To confirm: the above error occurs when using the latest TFF release `0.16.1`, but not in `0.15.0`? Would you mind describing any code changes you made to enable it to work, or even create a pull request with the fix?

On the last question about clients' updated weights, the IterativeProcess will need to be edited to return the values. This StackOverflow question maybe relevant? [Is there a way for TFF clients to have internal states?](https://stackoverflow.com/questions/63498907/is-there-a-way-for-tff-clients-to-have-internal-states)

**Comment by DemoAllan** [comment]
Yes. Using 0.15.0 can run this code. When using 0.16.1, errors will occur. After downloading emnist_target.mat and emnist_test_data.mat, I just changed two parts of the codes in order to read these two file correctly:
The `load_malicious_dataset(num_tasks) `function
```
#url_malicious_dataset = 'https://storage.googleapis.com/tff-experiments-public/targeted_attack/emnist_malicious/emnist_target.mat'
#filename = 'emnist_target.mat'
#path = tf.keras.utils.get_file(filename, url_malicious_dataset)
emnist_target_data = io.loadmat('data/emnist_target.mat')
```

And the `load_test_data()` function
```
#url_test_data = 'https://storage.googleapis.com/tff-experiments-public/targeted_attack/emnist_test_data/emnist_test_data.mat'
#filename = 'emnist_test_data.mat'
#path = tf.keras.utils.get_file(filename, url_test_data)
emnist_test_data = io.loadmat('data/emnist_test_data.mat')
```
'data' is the file where  `emnist_test_data.mat ` is stored.

Also, thank you for answering the second question. 

> To confirm: the above error occurs when using the latest TFF release `0.16.1`, but not in `0.15.0`? Would you mind describing any code changes you made to enable it to work, or even create a pull request with the fix?
> 
> On the last question about clients' updated weights, the IterativeProcess will need to be edited to return the values. This StackOverflow question maybe relevant? [Is there a way for TFF clients to have internal states?](https://stackoverflow.com/questions/63498907/is-there-a-way-for-tff-clients-to-have-internal-states)
