### ISSUE TITLE
TensorBoard errors in Federated Learning for Image Classification tutorial

### ISSUE THREAD

**Issue by conwaychriscosmo** [tensorflow/federated#914]
**Describe the bug**
Notebook: [Federated Learning for Image Classification Tutoria](https://colab.research.google.com/github/tensorflow/federated/blob/master/docs/tutorials/federated_learning_for_image_classification.ipynb#scrollTo=8BKyHkMxKHfV)l
Command:
```
#@test {"skip": true}
%tensorboard --logdir /tmp/logs/scalars/ --port=0

ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
2020-10-06 17:10:06.022164: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2020-10-06 17:10:06.022223: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/usr/local/bin/tensorboard", line 8, in <module>
    sys.exit(run_main())
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/main.py", line 75, in run_main
    app.run(tensorboard.main, flags_parser=tensorboard.configure)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/program.py", line 290, in main
    return runner(self.flags) or 0
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/program.py", line 306, in _run_serve_subcommand
    server = self._make_server()
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/program.py", line 416, in _make_server
    ingester.deprecated_multiplexer,
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/backend/application.py", line 149, in TensorBoardWSGIApp
    experimental_middlewares,
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/backend/application.py", line 257, in __init__
    "Duplicate plugins for name %s" % plugin.plugin_name
ValueError: Duplicate plugins for name projector 
```

**Environment (please complete the following information):**
* OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
* Python package versions (TensorFlow Federated, TensorFlow): TensorFlow Federated, TensorBoard
* Python version:python3.6
* Bazel version (if building from source):N/A using google collab environment
* CUDA/cuDNN version:
* What TensorFlow Federated execution stack are you using?

Note: You can collect the Python package information by running `pip3 freeze`
from the command line and most of the other information can be collected using
TensorFlows environment capture
[script](https://github.com/tensorflow/tensorflow/blob/master/tools/tf_env_collect.sh).

**Expected behavior**
I expected tensorboard to start.  I got an error that reflects issues in the underlying environment instead.

**Additional context**

**Comment by hbmcmahan** [comment]
I'm hoping to have a fix submitted soon, in the meantime I think changing the first cell along these lines should fix the issue:

```
# tensorflow_federated_nightly also bring in tf_nightly, which
# can causes a duplicate tensorboard install, leading to errors.
!pip uninstall --yes tensorboard tb-nightly

!pip install --quiet --upgrade tensorflow_federated_nightly
!pip install --quiet --upgrade nest_asyncio
!pip install --quiet tb-nightly  # or tensorboard, but not both
```
